import "./globals.css";
import NavBar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "קרקע להשקעה",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
